# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Use custom format
# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [shell]
# bash_indicator = "\uf120"
# disabled = false

# [cmd_duration]
# min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
# format = " [$duration]($style)"


[username]
style_user = "bold dimmed blue"
show_always = true
style_root = "black bold"
format = " [$user]($style) â¯ "




[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #f57800"
read_only = "ğŸ”’"
read_only_style = "red"


[conda]
symbol = "ï„Œ "


[python]
symbol = "î˜† "


[status]
format = "[$symbol$status]($style)"
symbol = "âœ–"
style = "bold red"
disabled = true
